// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xfmwmflwrznhdyfrdcjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhmbXdtZmx3cnpuaGR5ZnJkY2pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MDY4MjMsImV4cCI6MjA3Mjk4MjgyM30.f1iZXJu18s0l6QUFtGaRDpa1n-Lr6aJv8GExAESAbd0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});